proxy.port: 8020

logging.config: classpath:config/logback.xml
logging.level.io.netty.handler.logging.LoggingHandler: DEBUG

---
remoteHost: 127.0.0.1
remotePort: 8765

---

spring.profiles: prod

logging.file: ihooyah-proxy.log
logging.level.io.netty.handler.logging.LoggingHandler: INFO
